# Generated by Django 4.2.7 on 2025-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transfer_code',
            field=models.CharField(blank=True, default='00075', max_length=30, null=True),
        ),
    ]
