# Generated by Django 4.2.7 on 2025-01-20 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_transfer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dyczsxojr/image/upload/v1728295186/defaults_ty3sok.png', max_length=255, verbose_name='image'),
        ),
    ]
