# Generated by Django 4.2.7 on 2025-01-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountdetails_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdetails',
            options={'verbose_name': '1 -Fund Users Account', 'verbose_name_plural': '1 -Fund Users Accounts'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'Login History', 'verbose_name_plural': 'Login Histories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '2 -Manage Account', 'verbose_name_plural': '2 -Manage Accounts'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '3 -Manage Client Address', 'verbose_name_plural': '3 -Manage Client Address'},
        ),
    ]
