# Generated by Django 4.2.7 on 2025-01-16 09:01

import cloudinary.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH_APP', 'Cash App'), ('PAYPAL', 'PayPal'), ('ZELLE', 'Zelle'), ('PIX', 'PIX')], max_length=10)),
                ('name_tag', models.CharField(help_text='Cash App Tag or PayPal/Zelle identifier', max_length=100)),
                ('qr_code_image', cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image')),
                ('bank_image', cloudinary.models.CloudinaryField(blank=True, default='None', max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '8- Aza Detail',
                'verbose_name_plural': '8-Aza Details',
            },
        ),
        migrations.CreateModel(
            name='CRYPWALLETS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(blank=True, max_length=500, null=True)),
                ('bitcoin_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('ethereum', models.CharField(blank=True, max_length=500, null=True)),
                ('ethereum_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('usdt_erc20', models.CharField(blank=True, max_length=500, null=True)),
                ('usdt_erc20_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('tron', models.CharField(blank=True, max_length=500, null=True)),
                ('tron_qr_code', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': '7- WALLETS',
                'verbose_name_plural': '7-WALLETS',
            },
        ),
        migrations.CreateModel(
            name='MailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal_internationa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('recipient_bank_name', models.CharField(default='', max_length=200)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals_international', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manage Transfer_international',
                'verbose_name_plural': 'Manage Transfers_international',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('bank_sort_code', models.CharField(default='', max_length=200)),
                ('swift_code', models.CharField(default='', max_length=200)),
                ('recipient_bank_name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=80)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3-Manage Transfer',
                'verbose_name_plural': '3-Manage Transfers',
            },
        ),
        migrations.CreateModel(
            name='SUPPORT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.CharField(choices=[('Please Select Customer Service Department', 'Please Select Customer Service Department'), ('My Account Is Suspended/Blocked', 'My Account Is Suspended/Blocked'), ('Customer Services Department', 'Customer Services Department'), ('Account Department', 'Account Department'), ('Transfer Department', 'Transfer Department'), ('Card Services Department', 'Card Services Department'), ('Loan Department', 'Loan Department'), ('Bank Deposit Department', 'Bank Deposit Department')], max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '6- SUPPORT',
                'verbose_name_plural': '6- SUPPORT',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('ETHEREUM', 'Ethereum'), ('BITCOIN', 'Bitcoin'), ('GIFTCARD', 'Giftcard'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('giftcard_type', models.CharField(blank=True, choices=[('Select Giftcard', 'Select Giftcard'), ('APPLE', 'Apple'), ('GOOGLE', 'Google'), ('ITUNES', 'iTunes'), ('AMAZON', 'Amazon')], max_length=20, null=True)),
                ('giftcard_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.banktransfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1- Bank Deposit',
                'verbose_name_plural': '1- Bank Deposit',
            },
        ),
        migrations.CreateModel(
            name='PayBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=512)),
                ('address2', models.CharField(default='', max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('zipcode', models.CharField(max_length=512)),
                ('nickname', models.CharField(max_length=512)),
                ('delivery_method', models.CharField(choices=[('Paper Check', 'Paper Check'), ('Digital Receipt', 'Digital Receipt')], default='', max_length=200)),
                ('memo', models.CharField(default='', max_length=80)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('day', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '4-Manage Bills',
                'verbose_name_plural': '4-Manage Bills',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_facility', models.CharField(choices=[('Disaster Recovery Support', 'Disaster Recovery Support'), ('Healthcare Assistance Program', 'Healthcare Assistance Program'), ('Infrastructure Development Grant', 'Infrastructure Development Grant'), ('Education Support Fund', 'Education Support Fund'), ('Small Business Aid', 'Small Business Aid'), ('Refugee Resettlement Support', 'Refugee Resettlement Support'), ('Environmental Conservation Grant', 'Environmental Conservation Grant'), ('Agricultural Support Fund', 'Agricultural Support Fund'), ('Economic Stabilization Support', 'Economic Stabilization Support'), ('Housing Development Grant', 'Housing Development Grant'), ('Energy and Utilities Support', 'Energy and Utilities Support'), ('Water and Sanitation Support', 'Water and Sanitation Support'), ('Technology and Innovation Support', 'Technology and Innovation Support'), ('Women Empowerment Support', 'Women Empowerment Support'), ('Youth and Start-up Support', 'Youth and Start-up Support')], default='', max_length=40)),
                ('payment_tenure', models.CharField(choices=[('6 Months', '6 Months'), ('12 Months', '12 Months'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5 Years', '5 Years'), ('10 Years', '10 Years')], default='', max_length=40)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5- LOANS REQUEST',
                'verbose_name_plural': '5- LOANS REQUEST',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWITHDRAW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('TRON', 'Tron'), ('ETHEREUM', 'Ethereum'), ('BITCOIN', 'Bitcoin')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient_address', models.CharField(default='', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2- Crypto Withdrawal',
                'verbose_name_plural': '2-Crypto Withdrawals',
            },
        ),
        migrations.CreateModel(
            name='CHECK_DEPOSIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='deposits/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='deposits/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check Deposit',
                'verbose_name_plural': 'Check Deposits',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('V', 'Visa'), ('M', 'Mastercard'), ('D', 'Discover'), ('A', 'American Express'), ('CUP', 'China Union Pay'), ('DC', 'Dollar Card'), ('MC', 'Master Card'), ('VC', 'Visa Card'), ('JC', 'JCB Card'), ('AE', 'American Express'), ('UB', 'Union Bank Card'), ('BC', 'Bank Card'), ('EB', 'Eurocard'), ('NC', 'Nordic Card'), ('AC', 'Asian Card'), ('IC', 'International Card'), ('MC', 'Maestro Card'), ('EC', 'Eurocheque Card'), ('GC', 'Global Card'), ('UC', 'Uba Card'), ('FC', 'First Bank Card'), ('ZC', 'Zenith Bank Card'), ('AC', 'Access Bank Card'), ('GC', 'GTBank Card'), ('KC', 'Keystone Bank Card'), ('EC', 'Ecobank Card'), ('IC', 'UBA International Card'), ('OC', 'Other Card')], max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('card_owner', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Card',
                'verbose_name_plural': 'Client Cards',
            },
        ),
    ]
