# Generated by Django 4.2.7 on 2025-01-16 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': 'Manage Transfer', 'verbose_name_plural': 'Manage Transfers'},
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='approval_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='approval_doc'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='fee_receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fee_receipt'),
        ),
    ]
