# Generated by Django 4.2.7 on 2025-01-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_withdrawal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'verbose_name': '3- Aza Detail', 'verbose_name_plural': '3-Aza Details'},
        ),
        migrations.AlterModelOptions(
            name='crypwallets',
            options={'verbose_name': '4- WALLETS', 'verbose_name_plural': '4-WALLETS'},
        ),
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'verbose_name': '7- LOANS REQUEST', 'verbose_name_plural': '7- LOANS REQUEST'},
        ),
        migrations.AlterModelOptions(
            name='paybills',
            options={'verbose_name': '5-Manage Bills', 'verbose_name_plural': '5-Manage Bills'},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': '2 - Manage Transfer', 'verbose_name_plural': '2 -Manage Transfers'},
        ),
    ]
