# Generated by Django 4.2.7 on 2025-01-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_banktransfer_options_alter_crypwallets_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'CONTACT US',
                'verbose_name_plural': 'CONTACT US',
            },
        ),
    ]
