# Generated by Django 4.2.7 on 2025-01-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_wisewithdrawal_skrillwithdrawal_revolutwithdrawal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localwithdrawal',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, null=True),
        ),
    ]
